container:
  image: ghcr.io/cirruslabs/android-sdk:35
  kvm: true
  cpu: 8
  memory: 16G

instrumentation_tests_task:
  name: "Cirrus CI Instrumentation Tests"
  start_avd_background_script:
    sdkmanager --install "system-images;android-35;google_apis;x86_64" "emulator";
    echo no | avdmanager create avd -n seedvault -k "system-images;android-35;google_apis;x86_64";
    $ANDROID_HOME/emulator/emulator
    -avd seedvault
    -no-audio
    -no-boot-anim
    -gpu swangle_indirect
    -no-snapshot
    -no-window
    -writable-system;
  provision_avd_background_script:
    wget https://github.com/seedvault-app/seedvault-test-data/releases/download/3/backup.tar.gz;

    adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;';
    adb root;
    sleep 5;
    adb remount;
    adb reboot;
    adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;';
    adb root;
    sleep 5;
    adb remount;
    sleep 5;
  assemble_script:
    ./gradlew :app:assembleRelease :contacts:assembleRelease assembleAndroidTest
  install_app_script:
    timeout 180s bash -c 'while [[ -z $(adb shell mount | grep "/system " | grep "(rw,") ]]; do sleep 1; done;';
    adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;';

    for pkg in com.google.android.webview com.google.android.apps.photos com.google.android.youtube com.google.android.apps.youtube.music com.android.musicfx com.google.android.soundpicker com.android.soundpicker com.google.android.gm com.google.android.dialer com.google.android.apps.messaging com.android.mms.service com.google.android.cellbroadcastreceiver com.google.android.cellbroadcastservice com.android.cellbroadcastreceiver com.google.android.apps.docs com.google.android.calendar com.google.android.contacts com.google.android.deskclock com.android.providers.calendar com.android.providers.contacts com.google.android.apps.maps com.google.android.projection.gearhead com.android.chrome com.google.android.googlequicksearchbox com.google.android.as com.google.android.as.oss com.google.android.apps.customization.pixel com.android.wallpapercropper com.android.wallpaper.livepicker com.google.android.accessibility.switchaccess com.google.android.apps.accessibility.voiceaccess com.google.android.marvin.talkback com.android.systemui.accessibility.accessibilitymenu com.google.android.apps.wellbeing com.google.android.healthconnect.controller com.android.camera2 com.android.cameraextensions com.android.bips com.android.printspooler com.google.android.printservice.recommendation com.android.egg com.android.theme.font.notoserifsource com.google.android.federatedcompute com.google.android.ondevicepersonalization.services com.google.android.odad com.google.android.onetimeinitializer com.google.android.telephony.satellite com.google.android.apps.safetyhub com.android.DeviceAsWebcam com.android.dreams.basic com.google.android.tag; do adb shell pm disable-user --user 0 "$pkg" || echo "$pkg not found, skipping..."; done;

    adb shell mkdir -p /sdcard/seedvault_baseline;
    adb push backup.tar.gz /sdcard/seedvault_baseline/backup.tar.gz;
    adb shell tar xzf /sdcard/seedvault_baseline/backup.tar.gz --directory=/sdcard/seedvault_baseline;

    adb shell mkdir -p /system/priv-app/Seedvault;
    adb push app/build/outputs/apk/release/app-release.apk /system/priv-app/Seedvault/Seedvault.apk;
    adb push permissions_com.stevesoltys.seedvault.xml /system/etc/permissions/privapp-permissions-seedvault.xml;
    adb push allowlist_com.stevesoltys.seedvault.xml /system/etc/sysconfig/allowlist-seedvault.xml;

    adb shell mkdir -p /system/priv-app/ContactsBackup;
    adb push contactsbackup/build/outputs/apk/release/contactsbackup-release.apk /system/priv-app/ContactsBackup/contactsbackup.apk;
    adb push contactsbackup/default-permissions_org.calyxos.backup.contacts.xml /system/etc/default-permissions/default-permissions_org.calyxos.backup.contacts.xml;

    adb shell bmgr enable true;
    adb reboot;
    adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;';
    adb shell bmgr transport com.stevesoltys.seedvault.transport.ConfigurableBackupTransport;
    adb reboot;
    adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;';
    for folder in Audiobooks Documents Downloads DCIM Movies Music Pictures Podcasts Ringtones Notifications Alarms Recordings; do adb shell rm -Rf "/sdcard/$folder" || echo "/sdcard/$folder cleanup failed, skipping..."; done;
  run_large_tests_script: ./gradlew -Pandroid.testInstrumentationRunnerArguments.size=large :app:connectedAndroidTest
  run_other_tests_script: ./gradlew -Pandroid.testInstrumentationRunnerArguments.notAnnotation=androidx.test.filters.LargeTest connectedAndroidTest
  always:
    pull_screenshots_script:
      adb pull /sdcard/seedvault_test_results
    screenshots_artifacts:
      path: "seedvault_test_results/**/*.mp4"
    logcat_artifacts:
      path: "seedvault_test_results/**/*.log"
    report_artifacts:
      path: "app/build/reports/**/*"
