name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Gradle dependency cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Android build cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.android/build-cache
          key: ${{ runner.os }}-android
          restore-keys: ${{ runner.os }}-android

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: ./gradlew compileDebugAndroidTestSources check assemble ktlintCheck
